backend:
  name: github
  repo: ixiruido/patagoniacodexPRUEBA
  branch: main
  base_url: https://patagoniacodexprueba.ixi-b.workers.dev
  auth_endpoint: auth

media_folder: "src/assets/images"
public_folder: "/assets/images"

collections:
  - name: "pagina"
    label: "Página"
    files:
      - name: "home"
        label: "Página principal"
        file: "content/home.json"
        fields:
          - label: "Título"
            name: "titulo"
            widget: "string"

          - label: "Descripción"
            name: "descripcion"
            widget: "text"
