backend:
  name: github
  repo: ixiruido/patagoniacodexPRUEBA
  branch: main
  base_url: https://patagoniacodexprueba.ixi-b.workers.dev
  auth_endpoint: auth

media_folder: "src/assets/images"
public_folder: "/assets/images"

collections:
  - name: "home"
    label: "Página Principal"
    files:
      - name: "home"
        label: "Página Principal"
        file: "content/home.json"
        fields:
          - {label: "Título", name: "meta", widget: "object"}
          - {label: "Header", name: "header", widget: "object"}
          - {label: "Secciones", name: "secciones", widget: "list"}
          - {label: "Footer", name: "footer", widget: "object"}